version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5175:80"
    container_name: busca-cep-frontend
    restart: unless-stopped
    extra_hosts:
      - "custom-backend.local:host-gateway"
